<a href="https://colab.research.google.com/github/Waleed-Azam/1D-CNN/blob/master/X%20is%20real%20features%20and%20y%20is%20the%20label%20here%20to%20denoise.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
# univariate cnn example
from numpy import array
from keras.models import Sequential
from keras.layers import Dense
from keras.layers import Flatten
from keras.layers.convolutional import Conv1D
from keras.layers.convolutional import MaxPooling1D


Using TensorFlow backend.


In [0]:
!pip install -U -q PyDrive
from pydrive.auth import GoogleAuth
from pydrive.drive import GoogleDrive
from google.colab import auth
from oauth2client.client import GoogleCredentials
import numpy as np 
import matplotlib.pyplot as plt

In [0]:
auth.authenticate_user()
gauth = GoogleAuth()
gauth.credentials = GoogleCredentials.get_application_default()
drive = GoogleDrive(gauth)

In [0]:
downloaded = drive.CreateFile({'id':'1agv3WTJF7GiaUwWJGDpDQfZwX_nApM-J'}) # replace the id with id of file you want to access'}) # replace the id with id of file you want to access
#https://drive.google.com/file/d/1agv3WTJF7GiaUwWJGDpDQfZwX_nApM-J/view?usp=sharing

In [0]:
downloaded.GetContentFile('Dataa_True.csv')

In [6]:
import pandas as pd
df2 = pd.read_csv('Dataa_True.csv') 
df2

Time       TRUE       Srac
0         0.0   0.000000  20.000000
1         0.0  20.000000  20.000000
2         0.1  20.000000  20.000000
3         0.2  20.000000  20.000000
4         0.3  20.000000  20.000000
...       ...        ...        ...
49996  4999.5   2.367222   2.564293
49997  4999.6   2.366861   2.564267
49998  4999.7   2.366521   2.564253
49999  4999.8   2.366202   2.564248
50000  4999.9   2.365877        NaN

[50001 rows x 3 columns]

In [7]:
df2["TRUE"] = df2["TRUE"].fillna(0)
df2["Srac"] = df2["Srac"].fillna(0)
df2

Time       TRUE       Srac
0         0.0   0.000000  20.000000
1         0.0  20.000000  20.000000
2         0.1  20.000000  20.000000
3         0.2  20.000000  20.000000
4         0.3  20.000000  20.000000
...       ...        ...        ...
49996  4999.5   2.367222   2.564293
49997  4999.6   2.366861   2.564267
49998  4999.7   2.366521   2.564253
49999  4999.8   2.366202   2.564248
50000  4999.9   2.365877   0.000000

[50001 rows x 3 columns]

In [0]:
t=df2['Time']
Label=df2['TRUE']
y=np.array( Label)
X=df2['Srac']
X=np.array(X)
import numpy as np

In [0]:
def split_sequence(sequence, n_steps):
	X, z = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_z = sequence[i:end_ix], sequence[end_ix]
		X.append(seq_x)
		z.append(seq_z)
	return array(X), array(z)

In [11]:
X

array([20.      , 20.      , 20.      , ...,  2.564253,  2.564248,
        0.      ])

In [12]:
X.shape

(50001,)

In [0]:
# define input sequence
raw_seq = X
# choose a number of time steps
n_steps = 3
# split into samples
X, z = split_sequence(raw_seq, n_steps)

In [14]:
X

array([[20.      , 20.      , 20.      ],
       [20.      , 20.      , 20.      ],
       [20.      , 20.      , 20.      ],
       ...,
       [ 2.564325,  2.564293,  2.564267],
       [ 2.564293,  2.564267,  2.564253],
       [ 2.564267,  2.564253,  2.564248]])

In [15]:
X.shape

(49998, 3)

In [16]:
z

array([20.      , 20.      , 20.      , ...,  2.564253,  2.564248,
        0.      ])

In [17]:
z.shape

(49998,)

In [18]:
Label

0         0.000000
1        20.000000
2        20.000000
3        20.000000
4        20.000000
           ...    
49996     2.367222
49997     2.366861
49998     2.366521
49999     2.366202
50000     2.365877
Name: TRUE, Length: 50001, dtype: float64

In [19]:
Label.shape

(50001,)

In [0]:
# split a univariate sequence into samples
def split_sequence(sequence, n_steps):
	Label, y = list(), list()
	for i in range(len(sequence)):
		# find the end of this pattern
		end_ix = i + n_steps
		# check if we are beyond the sequence
		if end_ix > len(sequence)-1:
			break
		# gather input and output parts of the pattern
		seq_x, seq_y = sequence[i:end_ix], sequence[end_ix]
		Label.append(seq_x)
		y.append(seq_y)
	return array(Label), array(y)

In [0]:
# define input sequence
raw_seq = Label
# choose a number of time steps
n_steps = 3
# split into samples
Label, y = split_sequence(raw_seq, n_steps)
# reshape from [samples, timesteps] into [samples, timesteps, features]
n_features = 1
Label = Label.reshape((Label.shape[0], Label.shape[1], n_features))

In [23]:
Label

array([[[ 0.      ],
        [20.      ],
        [20.      ]],

       [[20.      ],
        [20.      ],
        [20.      ]],

       [[20.      ],
        [20.      ],
        [20.      ]],

       ...,

       [[ 2.367604],
        [ 2.367222],
        [ 2.366861]],

       [[ 2.367222],
        [ 2.366861],
        [ 2.366521]],

       [[ 2.366861],
        [ 2.366521],
        [ 2.366202]]])

In [24]:
Label.shape

(49998, 3, 1)

In [25]:
y

array([20.      , 20.      , 20.      , ...,  2.366521,  2.366202,
        2.365877])

In [26]:
y.shape

(49998,)